apiVersion: apps/v1
kind: Deployment
metadata:
 name: test
 namespace: demo
spec:
 replicas: 2
 selector:
   matchLabels:
     app: test
 template:
   metadata:
     labels:
       app: test
   spec:
     containers:
     - name: test
       image: nginx
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: test
 namespace: demo
spec:
 ports:
   - name: test-port
     port: 80
     targetPort: 80
 selector:
   app: test
 type: NodePort
